[theme]
primaryColor = "#087F75"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172B3A"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
